from . import account_import_padron_ret_perc
from . import account_move_line
from . import account_move
from . import account_padron_retention_perception_line
from . import account_padron_retention_perception_type
from . import account_payment_group
from . import padron_update_cron
from . import res_partner_arba_alicuot
from . import res_partner